DROP DATABASE IF EXISTS cuotasdb;
DROP USER IF EXISTS `cuotasadmin`@`%`;
CREATE DATABASE IF NOT EXISTS cuotasdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `cuotasadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `cuotasdb`.* TO `cuotasadmin`@`%`;